---
abstract: 'Travis CI plugins for your DZIL-based distribution'
author:
  - 'Brendan Byrd <BBYRD@CPAN.org>'
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license:
  - artistic_2
meta-spec:
  url: http://search.cpan.org/perldoc?CPAN::Meta::Spec
  version: 2
name: Dist-Zilla-TravisCI
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
prereqs:
  runtime:
    requires:
      Acme::Indent: 0.01
      Dist::Zilla: 1.093220
      Dist::Zilla::Plugin::Git::Check: 1.093250
      Dist::Zilla::Role::Git::DirtyFiles: 1.100740
      Dist::Zilla::Role::Git::LocalRepository: v0.1.1
      Dist::Zilla::Role::Git::Remote: v0.1.1
      Dist::Zilla::Role::Git::Remote::Branch: v0.1.1
      Dist::Zilla::Role::Git::Remote::Check: v0.1.1
      Dist::Zilla::Role::Git::Remote::Update: v0.1.1
      Dist::Zilla::Role::MetaCPANInterfacer: 0.90
      File::Slurp: 9999.14
      List::AllUtils: 0.01
      Moose: 0.34
      Moose::Autobox: 0.09
      MooseX::Has::Sugar: 0.0100
      MooseX::Types::Moose: 0
      perl: v5.10.1
      sanity: 0.91
  test:
    requires:
      Test::CheckDeps: 0.002
      Test::UseAllModules: 0.10
provides:
  Dist::Zilla::App::Command::chainsmoke:
    file: lib/Dist/Zilla/App/Command/chainsmoke.pm
    version: 0.90
  Dist::Zilla::App::CommandHelper::ChainSmoking:
    file: lib/Dist/Zilla/App/CommandHelper/ChainSmoking.pm
    version: 0.90
  Dist::Zilla::Plugin::TravisYML:
    file: lib/Dist/Zilla/Plugin/TravisYML.pm
    version: 0.90
  Dist::Zilla::Role::TravisYML:
    file: lib/Dist/Zilla/Role/TravisYML.pm
    version: 0.90
release_status: stable
resources:
  bugtracker:
    web: https://github.com/SineSwiper/Dist-Zilla-TravisCI/issues
  homepage: https://github.com/SineSwiper/Dist-Zilla-TravisCI/wiki
  repository:
    type: git
    url: git://github.com/SineSwiper/Dist-Zilla-TravisCI.git
    web: https://github.com/SineSwiper/Dist-Zilla-TravisCI
  x_irc: irc://irc.perl.org/#distzilla
version: 0.90
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::ReportPhase
      name: ReportPhase
      version: 0.00
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: MakeMaker
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: Git::NextVersion
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: Git::GatherDir
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: OurPkgVersion
      version: 0.004000
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: PodWeaver
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: PruneCruft
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::GitFmtChanges
      name: GitFmtChanges
      version: 0.005
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: ManifestSkip
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::Manifest
      name: Manifest
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::License
      name: License
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: ReadmeHtmlInBuild
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: ReadmePodInBuild
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: InstallGuide
      version: 1.200000
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: ExecDir
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: Test::Compile
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      name: RunExtraTests
      version: 0.007
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: NoTabsTests
      version: 0.01
    -
      class: Dist::Zilla::Plugin::Test::EOL
      name: Test::EOL
      version: 0.07
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Meta::JSON
      name: Test::CPAN::Meta::JSON
      version: 0.003
    -
      class: Dist::Zilla::Plugin::Test::CheckDeps
      name: Test::CheckDeps
      version: 0.005
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: Test::Portability
      version: 2.000003
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: Test::MinimumVersion
      version: 2.000002
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: ReportVersions::Tiny
      version: 1.05
    -
      class: Dist::Zilla::Plugin::Test::CheckManifest
      name: Test::CheckManifest
      version: 0.03
    -
      class: Dist::Zilla::Plugin::Test::DistManifest
      name: Test::DistManifest
      version: 2.000002
    -
      class: Dist::Zilla::Plugin::Test::UseAllModules
      name: Test::UseAllModules
      version: 0.002
    -
      class: Dist::Zilla::Plugin::Test::Version
      name: Test::Version
      version: 0.002004
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Prereqs/AutoPrereqs'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Prereqs/MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::MinimumPrereqs
      name: '@Prereqs/MinimumPrereqs'
      version: 0.91
    -
      class: Dist::Zilla::Plugin::PrereqsClean
      name: '@Prereqs/PrereqsClean'
      version: 0.91
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: CheckPrereqsIndexed
      version: 0.007
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: MetaYAML
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: MetaProvides::Package
      version: 1.14000001
    -
      class: Dist::Zilla::Plugin::MetaResourcesFromGit
      name: MetaResourcesFromGit
      version: 1.103620
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: CopyFilesFromBuild
      version: 0.103510
    -
      class: Dist::Zilla::Plugin::TravisYML
      name: TravisYML
      version: ~
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: Git::CheckFor::CorrectBranch
      version: 0.004
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: Git::CommitBuild
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Git/Check'
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Git/Commit'
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Git/Tag'
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Git/Push'
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: TestRelease
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: ConfirmRelease
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: UploadToCPAN
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: InstallRelease
      version: 0.008
    -
      class: Dist::Zilla::Plugin::Clean
      name: Clean
      version: 0.04
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300020
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300020
