---
abstract: 'Travis CI plugins for your DZIL-based distribution'
author:
  - 'Brendan Byrd <bbyrd@cpan.org>'
build_requires:
  Dist::Zilla: 0
  Test::CheckDeps: 0.002
  Test::DZil: 4.200002
  Test::More: 0.94
  Test::Most: 0.01
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.130880'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-TravisCI
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Dist::Zilla::App::Command::chainsmoke:
    file: lib/Dist/Zilla/App/Command/chainsmoke.pm
    version: 1.03
  Dist::Zilla::App::CommandHelper::ChainSmoking:
    file: lib/Dist/Zilla/App/CommandHelper/ChainSmoking.pm
    version: 1.03
  Dist::Zilla::Plugin::TravisYML:
    file: lib/Dist/Zilla/Plugin/TravisYML.pm
    version: 1.03
  Dist::Zilla::Role::TravisYML:
    file: lib/Dist/Zilla/Role/TravisYML.pm
    version: 1.03
requires:
  Dist::Zilla: 1.093220
  Dist::Zilla::Plugin::Git::Check: 1.093250
  Dist::Zilla::Role::Git::DirtyFiles: 1.100740
  Dist::Zilla::Role::Git::LocalRepository: v0.1.1
  Dist::Zilla::Role::Git::Remote: v0.1.1
  Dist::Zilla::Role::Git::Remote::Branch: v0.1.1
  Dist::Zilla::Role::Git::Remote::Check: v0.1.1
  Dist::Zilla::Role::Git::Remote::Update: v0.1.1
  Dist::Zilla::Role::Git::Repo: 1.113220
  Dist::Zilla::Role::MetaCPANInterfacer: 0.90
  File::Slurp: 9999.14
  List::AllUtils: 0.01
  Moose: 0.34
  Moose::Autobox: 0.09
  MooseX::Has::Sugar: 0.0100
  MooseX::Types::Moose: 0
  YAML: 0.67
  perl: v5.10.1
  sanity: 0.91
resources:
  X_irc: irc://irc.perl.org/#distzilla
  bugtracker: https://github.com/SineSwiper/Dist-Zilla-TravisCI/issues
  homepage: https://github.com/SineSwiper/Dist-Zilla-TravisCI/wiki
  repository: git://github.com/SineSwiper/Dist-Zilla-TravisCI.git
version: 1.03
x_Dist_Zilla:
  perl:
    version: 5.014002
  plugins:
    -
      class: Dist::Zilla::Plugin::ReportPhase
      name: '@Filter/ReportPhase'
      version: 0.03
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/MakeMaker'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::ModuleShareDirs
      name: '@Filter/ModuleShareDirs'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Filter/Git::NextVersion'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@Filter/Git::GatherDir'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: '@Filter/OurPkgVersion'
      version: 0.004000
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Filter/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::GitFmtChanges
      name: '@Filter/GitFmtChanges'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Filter/ReadmePodInRoot'
      version: 0.131500
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Filter/ReadmeTextInBuild'
      version: 0.131500
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Filter/ReadmeHTMLInBuild'
      version: 0.131500
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@Filter/InstallGuide'
      version: 1.200000
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@Filter/Test::Compile'
      version: 2.002
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      name: '@Filter/RunExtraTests'
      version: 0.011
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@Filter/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::Test::EOL
      name: '@Filter/Test::EOL'
      version: 0.07
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Meta::JSON
      name: '@Filter/Test::CPAN::Meta::JSON'
      version: 0.003
    -
      class: Dist::Zilla::Plugin::Test::CheckDeps
      name: '@Filter/Test::CheckDeps'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: '@Filter/Test::Portability'
      version: 2.000004
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Filter/Test::MinimumVersion'
      version: 2.000005
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@Filter/Test::ReportPrereqs'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Test::CheckManifest
      name: '@Filter/Test::CheckManifest'
      version: 0.04
    -
      class: Dist::Zilla::Plugin::Test::DistManifest
      name: '@Filter/Test::DistManifest'
      version: 2.000003
    -
      class: Dist::Zilla::Plugin::Test::Version
      name: '@Filter/Test::Version'
      version: 0.002004
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Filter/@Prereqs/AutoPrereqs'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Filter/@Prereqs/MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::MinimumPrereqs
      name: '@Filter/@Prereqs/MinimumPrereqs'
      version: 0.92
    -
      class: Dist::Zilla::Plugin::PrereqsClean
      name: '@Filter/@Prereqs/PrereqsClean'
      version: 0.92
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@Filter/CheckPrereqsIndexed'
      version: 0.009
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@Filter/MetaNoIndex'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@Filter/MetaProvides::Package'
      version: 1.14000002
    -
      class: Dist::Zilla::Plugin::MetaResourcesFromGit
      name: '@Filter/MetaResourcesFromGit'
      version: 1.103620
    -
      class: Dist::Zilla::Plugin::ContributorsFromGit
      name: '@Filter/ContributorsFromGit'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@Filter/CopyFilesFromBuild'
      version: 0.103510
    -
      class: Dist::Zilla::Plugin::TravisYML
      name: '@Filter/TravisYML'
      version: 1.03
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@Filter/Git::CheckFor::CorrectBranch'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@Filter/Git::CommitBuild'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Filter/@Git/Check'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Filter/@Git/Commit'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/@Git/Tag'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Filter/@Git/Push'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@Filter/GitHub::Update'
      version: 0.34
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/TestRelease'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/ConfirmRelease'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Filter/InstallRelease'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::Clean
      name: '@Filter/Clean'
      version: 0.07
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300035
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300035
x_contributors:
  - 'Graham Knop <haarg@haarg.org>'
  - 'Torsten Raudssus <torsten@raudss.us>'
